@startuml
skinparam monochrome true

rectangle "FFC" {
    [AirSync]
    [App]
    [API]
    [Entity]
}

[JHCIS] -> [AirSync]
[App] --> [API]
[AirSync] --> [API]
[API] --> [Entity]
[App] --> [Genogram]
[API] -> [Genogram]
[App] -> [TAI/ADL]

@enduml
