@startuml
skinparam monochrome true

rectangle "PCU" <<Private Network>> {
    [AirSync] as AirSync
    frame "HIS" {
        [JHCIS] as J
        database "JHCIS\nDatabase" {
            [data] as JDB
        }
    }
    AirSync -up- JDB
    JDB = J
}

cloud Cloud {
  frame FFC {
      [API] <<RESTful>> as API
      database "Database" {
        [Data]
      }
      [Console] <<html>>
      Console --> API : via
      API -down- Data
  }
  frame "BeeStorage" {
      [Controller] <<Thumbor>> as Img
       database "Storage" {
          [Image Data] as ImgData
       }
        Img - ImgData
  }
  () https
  [Load Balancer] <<Proxy>> as Proxy
  Proxy -up- https
  Proxy -left. API : api.ffc.in.th
  Proxy -. Img : img.ffc.in.th

  [Console] .. Proxy : console.ffc.in.th

}

cloud "Push Notification \nService Provider" {
   () Messaging
}

rectangle Mobile {
    [Application] as app
}

API --> Messaging : Push
Messaging ..> app : Notify
Messaging ...> AirSync : Notify

AirSync ---> https : api
app ---> https : api

actor "HealthCare\n Provider" as Provider
Provider <<Care Manager>>
Provider -- J
Provider - app

actor Surveyor
Surveyor <<Care Giver>>
app -- Surveyor

actor Admin
() "Web Browser" as web
web -up-- Admin
web --> https : console

@enduml
