@startuml
left to right direction
skinparam monochrome true

actor :Health Care\nProvider: as Provider <<Care Manaer>>
actor Surveyor <<Care Giver>>
actor Patient
actor Analyzer <<Machine>> as AI

Provider -right--|> Surveyor

rectangle Healthcare-Service {
    Provider -- (HomeVisit) : View History /\n Home Visit
    (Service) .> (HomeVisit) : <<extend>>
    (Service) -- Patient
    (Service) -- AI : Analyze
    (Service) <. (Patient\nInfomation) : <<include>>
    (Genogram) <. (Patient\nInfomation) : <<include>>
    (Patient\nInfomation) -- Patient
    (Suggestion) -- AI : Analyze result
    Provider -- (Suggestion) : Receive / Alert
    Surveyor --  (Patient\nInfomation) : View
}

rectangle Community {
    Surveyor -- (Place) : Update
    (Place) <. (Resident): <<include>>
    (Place Location) <. (Place) : <<extend>>
    (Resident) -- (Patient)
    (Community Maps) .> (Place Location) : <<include>>
    Surveyor -- (Community Maps) : View
}

@enduml
